apiVersion: v1
kind: Service
metadata:
  name: speakwithgemini-service
spec:
  selector:
    app: speakwithgemini
  ports:
    - protocol: TCP
      port: 80          # External port
      targetPort: 8000  # Port inside the container
  type: LoadBalancer  # Change to ClusterIP or NodePort if needed
